CXX		=	g++
CXXFLAGS	=	 

all:		runme

runme:	project.cpp dijkstrawithheap.cpp  dijkstrawithoutheap.cpp  graph.cpp  heapforkruskal.cpp  kruskal.cpp  maxheap.cpp dijkstrawithheap.h  dijkstrawithoutheap.h  graph.h  heapforkruskal.h  kruskal.h  maxheap.h

		$(CXX) $(CXXFLAGS) -o runme project.cpp dijkstrawithheap.cpp  dijkstrawithoutheap.cpp  graph.cpp  heapforkruskal.cpp  kruskal.cpp  maxheap.cpp 

clean:
		rm -f runme
